volumes:
  # devcontainerの拡張機能を毎回インストールするのを抑制する。
  vscode-server-extensions:

services:
  web: # サービス名
    tty: true
    stdin_open: true
    build: . # Dockerfileがあるディレクトリのパス
    ports:
      - "5000:5000" # `<ホストのポート>:<コンテナのポート>` の形式
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=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
    volumes:
      - ./app:/app # ローカルのディレクトリをコンテナにマウント（オプション）
      - vscode-server-extensions:/root/.vscode-server/extensions
    command: python app.py # コンテナの起動コマンド（オプション）

networks:
  default:
    external: true
    name: local_dev_network
